### PR TITLE
Add crystal support

### PR DESCRIPTION
**Pull request by mathisto**
### Ruby and Crystal are TWINSIES!!
SAMESIES!!

With almost identical syntax, this extension was just begging for [Crystal](https://crystal-lang.org) support. 

This PR:
- Adds a `OPENINGS` entry for crystal `enum` blocks
- Adds crystal to the activations array 
- Checks for a language match of `ruby` OR `crystal` in the keybinding when clauses
- Updates `README.md` to reflect added support for Crystal
- **BONUS**  - Updates your `LICENSE` year to 2021
- **BONUS**  - Updates your copyright year to 2021

### CODE REVIEW

**Comment by mathisto** [comment]
I just noticed there was a PR already opened with this. DOH!

**Comment by kaiwood** [comment]
@mathisto Naah, not so fast. This one has at least a bit more meat - and its about time for me to finally set some time aside to tackle this ;)

I'm still not using any Crystal, so my knowledge there is pretty thin.

`enum` is already in this PR, good. I also know of `struct` (does this even have an `end`, or is it all curly braces?)

Do you know of any other syntax that is missing?

If we get it at least somewhat complete, I'm absolutely willing to merge it and handle the rest to push things forward 🤷‍♂️

**Comment by mathisto** [comment]
Fantastic! What we have here, I actually am running locally with great success. I'll dig through the Crystal API docs and see what other blocks might benefit.

**Comment by mathisto** [comment]
Great call on [struct](https://crystal-lang.org/reference/syntax_and_semantics/structs.html).

I also added:
- [macro](https://crystal-lang.org/reference/syntax_and_semantics/macros/index.html)
- [annotation](https://crystal-lang.org/reference/syntax_and_semantics/annotations/index.html)
- [lib](https://crystal-lang.org/reference/syntax_and_semantics/c_bindings/lib.html)
- [union](https://crystal-lang.org/reference/syntax_and_semantics/c_bindings/union.html)

**Comment by mathisto** [comment]
So my Crystal is decent, buy my JS is garbagé. While, I think this will work pretty well as is, ideally, you might want to create a data structure for the `OPENINGS` const. You could then have activations for ruby that only used the elements from the `shared` list and activations for Crystal that used a concatenation of both `shared` and `crystal`.  Something like:
```json
const OPENINGS = {
  "shared": [
  /^\s*?if(\s|\()/,
  /^\s*?unless(\s|\()/,
  /^\s*?while(\s|\()/,
  /^\s*?for(\s|\()/,
  /\s?do(\s?$|\s\|.*\|\s?$)/,
  /^\s*?def\s/,
  /^\s*?class\s/,
  /^\s*?module\s/,
  /^\s*?case(\s|\()/,
  /^\s*?begin\s/,
  /^\s*?until(\s|\()/
],
  "crystal": [
  /^\s*?enum\s/,
  /^\s*?struct\s/,
  /^\s*?macro\s/,
  /^\s*?union\s/,
  /^\s*?lib\s/,
  /^\s*?annotation\s/
]};
```

**Comment by kaiwood** [comment]
Alright, finally found some time to finish this. I merged it and completed what was missing via #31 

Good call on the splitting things up. Its even necessary, otherwise it would break the language with the smaller subset of keywords (`annotation = "a string comment"` is a valid variable declaration in Ruby)

And to clarify my reasoning: If you check https://github.com/kaiwood/vscode-endwise/pull/31/commits/cd590fbc8f1e09fdeda4fb24c1eff8844a3658d3, you will see that I separated the languages completely. Having a "shared" thingy will only create hassle in the long run, because we would need to shuffle the entries around whenever a new language gets added.

I will try to clear the rest of the open things in this repo and then prepare a new release. Might take another day or so, it's already late over here.

Thanks a lot for pushing this forward! ;)

**Comment by kaiwood** [comment]
Release is out.

**Comment by mathisto** [comment]
HORAY! Great work my friend!

**Pull request merged**
